"""# Public API for Jest rules
"""

load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@aspect_bazel_lib//lib:utils.bzl", "default_timeout", "to_label")
load("//jest/private:jest_test.bzl", jest_test_rule = "jest_test")

UPDATE_SNAPSHOTS_TARGET_SUFFIX = "_update_snapshots"

def _jest_from_node_modules(jest_rule, name, node_modules, auto_configure_reporters, **kwargs):
    data = kwargs.pop("data", [])

    jest_cli_dep = "{}/jest-cli".format(node_modules)
    jest_unit_dep = "{}/jest-junit".format(node_modules)

    if jest_cli_dep not in data:
        data.append(jest_cli_dep)

    if auto_configure_reporters and jest_unit_dep not in data:
        data.append(jest_unit_dep)

    jest_rule(
        name = name,
        enable_runfiles = select({
            "@aspect_rules_js//js/private:enable_runfiles": True,
            "//conditions:default": False,
        }),
        unresolved_symlinks_enabled = select({
            "@aspect_rules_js//js/private:experimental_allow_unresolved_symlinks": True,
            "//conditions:default": False,
        }),
        data = data,
        testonly = True,
        auto_configure_reporters = auto_configure_reporters,
        **kwargs
    )

def jest_test(
        name,
        node_modules,
        config = None,
        data = [],
        snapshots = False,
        run_in_band = True,
        colors = True,
        auto_configure_reporters = True,
        auto_configure_test_sequencer = True,
        snapshots_ext = ".snap",
        quiet_snapshot_updates = False,
        timeout = None,
        size = None,
        **kwargs):
    """jest_test rule

    Supports Bazel sharding. See https://docs.bazel.build/versions/main/test-encyclopedia.html#test-sharding.

    Supports updating snapshots with `bazel run {name}_update_snapshots` if `snapshots` are specified.

    Args:
        name: A unique name for this target.

        node_modules: Label pointing to the linked node_modules target where jest is linked, e.g. `//:node_modules`.
            `jest-cli` must be linked into the node_modules supplied.
            `jest-junit` is also required by default when `auto_configure_reporters` is True.

            NB: Only the required npm packages are included in data from `//:node_modules`. Other npm packages
            are not included as inputs.

        config: "Optional Jest config file. See https://jestjs.io/docs/configuration.

            Supported config file types are ".js", ".cjs", ".mjs", ".json" which come from https://jestjs.io/docs/configuration
            minus TypeScript since we this rule extends from the configuration. TypeScript jest configs should be transpiled
            before being passed to jest_test with [rules_ts](https://github.com/aspect-build/rules_ts).

        data: Runtime dependencies of the Jest test.

            This should include all test files, configuration files & files under test.

        snapshots: If True, a `{name}_update_snapshots` binary target is generated that will update all existing `__snapshots__`
            directories when `bazel run`. This is the equivalent to running `jest -u` or `jest --updateSnapshot` outside of Bazel,
            except that new `__snapshots__` will not automatically be created on update. To bootstrap a new `__snapshots__` directory,
            you can create an empty one and then run the `{name}_update_snapshots` target to populate it.

            If the name of the snapshot directory is not the default `__snapshots__` because of a custom snapshot resolver,
            you can specify customize the snapshot directories with a `glob` or a static list. For example,

            ```
            jest_test(
                name = "test",
                node_modules = "//:node_modules",
                config = "jest.config.js",
                data = [
                    "greetings/greetings.js",
                    "greetings/greetings.test.js",
                    "link/link.js",
                    "link/link.test.js",
                ],
                snapshots = glob(["**/__snaps__"], exclude_directories = 0),
            )
            ```

            or with a static list,

            ```
                snapshots = [
                    "greetings/__greetings_snaps__",
                    "link/__link_snaps__",
                ]
            ```

            Snapshots directories must not contain any files except for snapshots. There must also be no BUILD files in
            the snapshots directories since they must be part of the same Bazel package that the `jest_test` target is in.

            If snapshots are _not_ configured to output to a directory that contains only snapshots, you may alternately
            set `snapshots` to a list of snapshot files expected to be generated by this `jest_test` target.
            These must be source files and all snapshots that are generated must be explicitly listed. You may use a
            `glob` such as `glob(["**/*.snap"])` to generate this list, in which case all snapshots must already be on
            disk so they are discovered by `glob`.

        run_in_band: When True, the `--runInBand` argument is passed to the Jest CLI so that all tests are run serially
            in the current process, rather than creating a worker pool of child processes that run tests. See
            https://jestjs.io/docs/cli#--runinband for more info.

            This is the desired default behavior under Bazel since Bazel expect each test process to use up one CPU core.
            To parallelize a single jest_test across many cores, use `shard_count` instead which is supported by `jest_test`.
            See https://docs.bazel.build/versions/main/test-encyclopedia.html#test-sharding.

        colors: When True, the `--colors` argument is passed to the Jest CLI. See https://jestjs.io/docs/cli#--colors.

        auto_configure_reporters: Let jest_test configure reporters for Bazel test and xml test logs.

            When enabled, `jest-junit` must be linked to the supplied node_modules tree.

            The `default` reporter is used for the standard test log and `jest-junit` is used for the xml log.
            These reporters are appended to the list of reporters from the user Jest `config` only if they are
            not already set.

            The `JEST_JUNIT_OUTPUT_FILE` environment variable is always set to where Bazel expects a test runner
            to write its xml test log so that if `jest-junit` is configured in the user Jest `config` it will output
            the junit xml file where Bazel expects by default.

        auto_configure_test_sequencer: Let jest_test configure a custom test sequencer for Bazel test that support Bazel sharding.

            Any custom testSequencer value in a user Jest `config` will be overridden.

            See https://jestjs.io/docs/configuration#testsequencer-string for more information on Jest testSequencer config option.

        snapshots_ext: The expected extensions for snapshot files. Defaults to `.snap`, the Jest default.

        quiet_snapshot_updates: When True, snapshot update stdout & stderr is hidden when the snapshot update is successful.

            On a snapshot update failure, its stdout & stderr will always be shown.

        timeout: standard attribute for tests. Defaults to "short" if both timeout and size are unspecified.

        size: standard attribute for tests

        **kwargs: Additional named parameters passed to both `js_test` and `js_binary`.
            See https://github.com/aspect-build/rules_js/blob/main/docs/js_binary.md
    """
    tags = kwargs.pop("tags", [])

    snapshot_data = []

    if snapshots == True:
        snapshots = native.glob(["**/__snapshots__"], exclude_directories = 0)

    if type(snapshots) == "string":
        snapshot_data = native.glob(["{}/**".format(snapshots)])
    elif type(snapshots) == "list":
        for snapshot in snapshots:
            snapshot_label = to_label(snapshot)
            if snapshot_label.package != native.package_name():
                msg = "Expected jest_test '{target}' snapshots to be in test target package '{jest_test_package}' but got '{snapshot_label}' in package '{snapshot_package}'".format(
                    jest_test_package = native.package_name(),
                    snapshot_label = snapshot_label,
                    snapshot_package = snapshot_label.package,
                    target = to_label(name),
                )
                fail(msg)
            if snapshot_label.name.endswith(snapshots_ext):
                snapshot_data.append(snapshot_label)
            else:
                snapshot_data.extend(native.glob(["{}/**".format(snapshot)]))

    elif snapshots != False and snapshots != None:
        msg = "snapshots expected to be a boolean, string or list but got {}".format(snapshots)
        fail(msg)

    entry_point = "_{}_jest_entrypoint".format(name)
    directory_path(
        name = entry_point,
        directory = "{}/jest-cli/dir".format(node_modules),
        path = "bin/jest.js",
    )

    bazel_sequencer = "_{}_bazel_sequencer".format(name)
    copy_file(
        name = bazel_sequencer,
        src = "@aspect_rules_jest//jest/private:bazel_sequencer.cjs",
        out = "_{}_bazel_sequencer.cjs".format(name),
        visibility = ["//visibility:public"],
    )

    bazel_snapshot_reporter = "_{}_bazel_snapshot_reporter".format(name)
    copy_file(
        name = bazel_snapshot_reporter,
        src = "@aspect_rules_jest//jest/private:bazel_snapshot_reporter.cjs",
        out = "_{}_bazel_snapshot_reporter.cjs".format(name),
        visibility = ["//visibility:public"],
    )

    bazel_snapshot_resolver = "_{}_bazel_snapshot_resolver".format(name)
    copy_file(
        name = bazel_snapshot_resolver,
        src = "@aspect_rules_jest//jest/private:bazel_snapshot_resolver.cjs",
        out = "_{}_bazel_snapshot_resolver.cjs".format(name),
        visibility = ["//visibility:public"],
    )

    # This is the primary {name} jest_test test target
    _jest_from_node_modules(
        jest_rule = jest_test_rule,
        name = name,
        node_modules = node_modules,
        config = config,
        data = data + snapshot_data,
        run_in_band = run_in_band,
        colors = colors,
        auto_configure_reporters = auto_configure_reporters,
        auto_configure_test_sequencer = auto_configure_test_sequencer,
        tags = tags,
        size = size,
        timeout = default_timeout(size, timeout),
        entry_point = entry_point,
        bazel_sequencer = bazel_sequencer,
        bazel_snapshot_reporter = bazel_snapshot_reporter,
        bazel_snapshot_resolver = bazel_snapshot_resolver,
        **kwargs
    )

    if snapshots != False:
        _jest_from_node_modules(
            jest_rule = jest_test_rule,
            name = name + UPDATE_SNAPSHOTS_TARGET_SUFFIX,
            node_modules = node_modules,
            config = config,
            # Also pass data to the tool for jest snapshot updates incase there are load bearing
            # data deps the config requires
            data = data,
            run_in_band = run_in_band,
            colors = colors,
            auto_configure_reporters = auto_configure_reporters,
            auto_configure_test_sequencer = auto_configure_test_sequencer,
            update_snapshots = True,
            quiet_snapshot_updates = quiet_snapshot_updates,
            entry_point = entry_point,
            bazel_sequencer = bazel_sequencer,
            bazel_snapshot_reporter = bazel_snapshot_reporter,
            bazel_snapshot_resolver = bazel_snapshot_resolver,
            tags = tags + ["manual"],  # tagged manual so it is not built unless the {name}_update_snapshot target is run
            **kwargs
        )
